customize:
    mysql:
        url: 192.168.235.233:3306
        username: root
        password: 123456

spring:
    application:
        name: activiti-project-flow
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://${customize.mysql.url}/activiti_qpf?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&&nullCatalogMeansCurrent=true&nullCatalogMeansCurrent=true&autoReconnect=true
            username: ${customize.mysql.username}
            password: ${customize.mysql.password}
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
    activiti:
        #1.flase：默认值。activiti在启动时，对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
        #2.true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
        #3.create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
        #4.drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
        database-schema-update: drop-create
        #activiti7默认不生成历史信息表，开启历史表
        db-history-used: true
        #记录历史等级 可配置的历史级别有none, activity, audit, full
        #none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
        #activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
        #audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
        #full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
        history-level: audit
        check-process-definitions: true
        # 执行定时任务
        async-executor-activate: true


    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    mvc:
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        prefix: classpath:/view/
        cache: false

logging:
    level:
        web: debug

